# Generated by Django 3.1.5 on 2021-01-23 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'appointment_types',
            },
        ),
        migrations.CreateModel(
            name='BattingStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'batting_styles',
            },
        ),
        migrations.CreateModel(
            name='BowlingStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'bowling_styles',
            },
        ),
        migrations.CreateModel(
            name='PlayingRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'playing_roles',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=80, null=True)),
                ('member_since', models.DateField(blank=True, null=True, verbose_name='Date Joined')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('active', models.BooleanField(blank=True, default=True)),
                ('batting_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='player.battingstyle')),
                ('bowling_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='player.bowlingstyle')),
                ('playing_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='player.playingrole')),
            ],
            options={
                'db_table': 'players',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(choices=[(1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021, verbose_name='Season')),
                ('appointment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='player.appointmenttype')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='player.player')),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['-season'],
            },
        ),
    ]
