# Generated by Django 3.1.5 on 2021-02-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bowler',
            name='overs',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Overs'),
        ),
    ]
