# Generated by Django 3.2 on 2021-04-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowler', '0002_auto_20210208_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='bowler',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Bowler Number'),
        ),
    ]
