# Generated by Django 3.1.5 on 2021-01-23 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'results',
            },
        ),
        migrations.CreateModel(
            name='MatchStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(blank=True, null=True, verbose_name='Report')),
                ('london_fields_overs', models.PositiveSmallIntegerField(null=True, verbose_name='London Fields Overs')),
                ('london_fields_score', models.PositiveSmallIntegerField(null=True, verbose_name='London Fields Score')),
                ('london_fields_wickets', models.PositiveSmallIntegerField(null=True, verbose_name='London Fields Wickets')),
                ('opposition_score', models.PositiveSmallIntegerField(null=True, verbose_name='Opposition score')),
                ('opposition_wickets', models.PositiveSmallIntegerField(null=True, verbose_name='Opposition Wickets')),
                ('opposition_overs', models.PositiveSmallIntegerField(null=True, verbose_name='Opposition overs')),
                ('london_fields_first_event', models.PositiveSmallIntegerField(choices=[(0, 'Batted'), (1, 'Bowled')], default=0, null=True)),
                ('report_byline', models.CharField(max_length=200, null=True)),
                ('report_author', models.CharField(max_length=200, null=True)),
                ('report_headline', models.CharField(max_length=200, null=True)),
                ('match', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='match.match')),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='match_statistics.result', verbose_name='Result')),
            ],
            options={
                'verbose_name_plural': 'Match Statistics',
                'db_table': 'matches_statistics',
                'ordering': ('match',),
            },
        ),
    ]
