# Generated by Django 3.1.5 on 2021-02-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchstatistics',
            name='london_fields_overs',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='London Fields Overs'),
        ),
        migrations.AlterField(
            model_name='matchstatistics',
            name='opposition_overs',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='Opposition overs'),
        ),
    ]
