# Generated by Django 3.1.5 on 2021-01-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('site', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oppositions',
                'ordering': ['name'],
            },
        ),
    ]
