# Generated by Django 3.1.5 on 2021-01-23 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('match', '__first__'),
        ('player', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('text', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'news_items',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=20)),
                ('url', models.URLField()),
                ('date', models.DateTimeField()),
                ('player', models.ManyToManyField(to='player.Player')),
            ],
            options={
                'db_table': 'podcasts',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=20)),
                ('date', models.PositiveIntegerField()),
                ('upload_date', models.DateTimeField()),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='match.match')),
                ('player', models.ManyToManyField(to='player.Player')),
            ],
            options={
                'db_table': 'pictures',
                'ordering': ['date'],
            },
        ),
    ]
