# Generated by Django 3.1.5 on 2021-01-23 22:31

# Django imports
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('match_statistics', '__first__'),
        ('batsman', '__first__'),
        ('bowler', '__first__'),
        ('match', '__first__'),
        ('player', '__first__')
    ]

    operations = [
        migrations.RunSQL("""
        CREATE VIEW bowler_all_seasons AS 
            SELECT players.id , concat(players.first_name, ' ', players.last_name) as name, matches.season,
            SUM(bowlers.wickets) as total
            FROM bowlers
            JOIN matches_statistics ON (bowlers.match_statistics_id = matches_statistics.id)
            JOIN matches ON (matches_statistics.match_id = matches.id)
            JOIN players ON (bowlers.player_id = players.id)
            GROUP BY 1,2,3;
        """),
        migrations.RunSQL("""
        CREATE VIEW batsmen_all_season AS 
            SELECT players.id, concat(players.first_name, ' ', players.last_name) as name, matches.season,
            SUM(batsmen.runs) as total
            FROM batsmen
            JOIN matches_statistics ON (batsmen.match_statistics_id = matches_statistics.id)
            JOIN matches ON (matches_statistics.match_id = matches.id)
            JOIN players ON (batsmen.player_id = players.id)
            WHERE players.first_name!='Extras'
            GROUP BY 1,2,3;
        """)
    ]
