# Generated by Django 3.1.5 on 2021-01-23 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venue', '__first__'),
        ('player', '__first__'),
        ('opposition', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'home_away',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(choices=[(1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021, verbose_name='Season')),
                ('date', models.DateField(verbose_name='Date')),
                ('remarks', models.CharField(max_length=200, null=True, verbose_name='Remarks')),
                ('home_or_away', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='match.homeaway', verbose_name='Home or Away')),
            ],
            options={
                'verbose_name_plural': 'matches',
                'db_table': 'matches',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MatchType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'match_types',
            },
        ),
        migrations.CreateModel(
            name='PlayerSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'player_skills',
            },
        ),
        migrations.CreateModel(
            name='PlayerMatchAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain', models.BooleanField(default=False, null=True, verbose_name='Captain')),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='match.match')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.player')),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='match.playerskill', verbose_name='Skill Set')),
            ],
            options={
                'db_table': 'player_match_attributes',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='mtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='match.matchtype', verbose_name='Match Type'),
        ),
        migrations.AddField(
            model_name='match',
            name='opposition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='opposition.opposition'),
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(blank=True, through='match.PlayerMatchAttribute', to='player.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='venue.venue'),
        ),
    ]
