WICKET_TYPES = (
    ("C", "CAUGHT"),
    ("BOW", "BOWLED"),
    ("RO", "RUN OUT"),
    ("RETH", "RETIRED HURT"),
    ("RETO", "RETIRED OUT"),
    ("CBOWL", "CAUGHT & BOWLED"),
    ("CBEH", "CAUGHT BEHIND"),
    ("DNB", "DID NOT BAT"),
    ("NO", "NOT OUT"),
    ("HB", "HANDLED BALL"),
    ("HBT", "HIT BALL TWICE"),
    ("HW", "HIT WICKET"),
    ("LBW", "LBW"),
    ("OF", "OBSTRUCTING FIELD"),
    ("S", "STUMPED"),
    ("TO", "TIMED OUT"),
    ("U", "UNKNOWN"),
)
