# Generated by Django 3.1.5 on 2021-01-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.URLField(blank=True, null=True, verbose_name='Map link to the venue')),
            ],
            options={
                'db_table': 'venues',
                'ordering': ['name'],
            },
        ),
    ]
