# Generated by Django 3.1.5 on 2021-01-23 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('match_statistics', '__first__'),
        ('player', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='WicketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'wicket_types',
            },
        ),
        migrations.CreateModel(
            name='Batsman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoring', models.CharField(blank=True, max_length=200, verbose_name='Scoring')),
                ('runs', models.PositiveIntegerField(blank=True, verbose_name='Runs')),
                ('bowler', models.CharField(blank=True, max_length=25, verbose_name='Bowler')),
                ('how_out', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='batsman.wickettype')),
                ('match_statistics', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='match_statistics.matchstatistics')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='player.player')),
            ],
            options={
                'verbose_name_plural': 'Batsmen',
                'db_table': 'batsmen',
                'ordering': ['match_statistics__match__date'],
            },
        ),
    ]
